apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  # add a label to the nodes on which this config should apply
  nodeSelector:
    matchLabels:
      bgp: "65002"
  bgpInstances:
  - name: "udm-65000"
    localASN: 65002
    peers:
    # BGP routers to peer with below
    - name: "peer-65000-udm"
      peerASN: 65000
      peerAddress: "192.168.1.1"
      peerConfigRef:
        name: "cilium-peer"

